
---
- name: build
  hosts: build
  become: yes
  tasks:
       - name: Install Of HTTPD  
         yum: 
          name: httpd
          state: absent

       - name: Ensure HTTPD Service Started 
         service: 
           name: httpd
           state: started 

       - name: Ensure HTTPD Service Started
         service:
           name: httpd
           enabled: yes


...
